name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Triggers on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # permissions for pushing to GitHub Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Matches GitLab's artifact path
